SELECT A.INV_NUM, A.LINE_NUM, A.PROD_SKU, A.PROD_DESCRIPT, B.LINE_NUM, 
  B.PROD_SKU, B.PROD_DESCRIPT, A.BRAND_ID 
FROM (SELECT L.INV_NUM, L.LINE_NUM, LP.PROD_SKU, 
    LP.PROD_DESCRIPT, LP.BRAND_ID, LP.PROD_CATEGORY       
  FROM LGLINE L, LGPRODUCT LP 
  WHERE L.PROD_SKU = LP.PROD_SKU 
  AND LP.PROD_CATEGORY = 'SEALER') A, 
  (SELECT L2.LINE_NUM, LP2.PROD_SKU, LP2.PROD_DESCRIPT, 
    LP2.BRAND_ID, L2.INV_NUM, LP2.PROD_CATEGORY
  FROM LGLINE L2, LGPRODUCT LP2 
  WHERE L2.PROD_SKU =LP2.PROD_SKU 
  AND LP2.PROD_CATEGORY = 'TOP COAT') B 
WHERE A.INV_NUM = B.INV_NUM 
AND A.BRAND_ID = B.BRAND_ID 
ORDER BY A.INV_NUM, A.LINE_NUM,B.LINE_NUM DESC;
