SELECT DISTINCT V.VEND_ID, V.VEND_NAME, B.BRAND_NAME, 
  COUNT(*) AS NUMPRODUCTS
FROM LGVENDOR V
INNER JOIN LGSUPPLIES S ON (V.VEND_ID = S.VEND_ID)
INNER JOIN LGPRODUCT P ON (S.PROD_SKU = P.PROD_SKU)
INNER JOIN LGBRAND B ON (P.BRAND_ID = B.BRAND_ID)
GROUP BY V.VEND_ID, V.VEND_NAME, B.BRAND_NAME
ORDER BY V.VEND_NAME ASC, B.BRAND_NAME ASC;
