SELECT B.BRAND_NAME AS BRAND_NAME, B.BRAND_TYPE AS BRAND_TYPE, P.PROD_SKU AS PROD_SKU, 
P.PROD_DESCRIPTION AS PROD_DESCRIPT, P.PROD_PRICE AS PROD_PRICE 
FROM LGBRAND B, LGPRODUCT P 
WHERE B.BRAND_ID=P.BRAND_ID 
AND B.BRAND_TYPE NOT IN ('PREMIUM') 
AND P.PROD_PRICE > 
(SELECT MAX(P.PROD_PRICE) 
FROM LGBRAND B, LGPRODUCT P 
WHERE B.BRAND_ID=P.BRAND_ID 
AND B.BRAND_TYPE = 'PREMIUM');
