CREATE TRIGGER trg_updatecustbalance2 
AFTER DELETE ON INV_MYSQL FOR EACH ROW
UPDATE CUST_MYSQL 
SET CUST_MYSQL.CUST_BALANCE = CUST_MYSQL.CUST_BALANCE - OLD.INV_AMOUNT 
WHERE CUST_MYSQL.CUST_NUM = OLD.CUST_NUM;

DELETE FROM INV_MYSQL WHERE INV_NUM = 9006;

SELECT * FROM INV_MYSQL;
SELECT * FROM CUST_MYSQL;