CREATE PROCEDURE prc_inv_delete(
	IN I_NUM INTEGER
)
DELETE FROM INV_MYSQL WHERE INV_NUM = I_NUM;

CALL prc_inv_delete(9000);
CALL prc_inv_delete(9001);

SELECT * FROM INV_MYSQL;
SELECT * FROM CUST_MYSQL;