SELECT C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME, C.CUST_STREET, 
C.CUST_CITY, C.CUST_STATE, C.CUST_ZIP, I.INV_DATE, 
I.INV_TOTAL AS 'Largest Invoice'
FROM LGCUSTOMER C, LGINVOICE I
WHERE I.CUST_CODE = C.CUST_CODE
	AND C.CUST_STATE = 'AL'
	AND I.INV_TOTAL = (
		SELECT MAX(I.INV_TOTAL) 
		FROM LGINVOICE I 
		WHERE I.CUST_CODE = C.CUST_CODE)
UNION
SELECT C2.CUST_CODE, C2.CUST_FNAME, C2.CUST_LNAME, C2.CUST_STREET, 
C2.CUST_CITY, C2.CUST_STATE, C2.CUST_ZIP, NULL, 0
FROM LGCUSTOMER C2
WHERE C2.CUST_STATE = 'AL'
	AND C2.CUST_CODE NOT IN (
		SELECT I.CUST_CODE 
		FROM LGINVOICE I)
ORDER BY CUST_LNAME, CUST_FNAME;
