UPDATE TABLE_NAME
SET COLUMN = [QUERY OR 'VALUE']
WHERE CONDITION;
UPDATION OF THE TABLE CHARTER
UPDATE CHARTER
SET CHAR_WAIT_CHG =
( SELECT MOD_WAIT_CHG FROM MODEL,AIRCRAFT WHERE MODEL.MOD_CODE = AIRCRAFT.MOD_CODE
AND AIRCRAFT.AC_NUMBER = CHARTER.AC_NUMBER);
