SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE,
EMP_LNAME,EMP_FNAME, EMP_INITIAL, 
EMPLOYEE.JOB_CODE, JOB_DESCRIPTION,JOB_CHG_HOUR
FROM PROJECT, EMPLOYEE, JOB
WHERE EMPLOYEE.EMP_NUM = PROJECT.EMP_NUM
AND JOB.JOB_CODE = EMPLOYEE.JOB_CODE
ORDER BY EMP_LNAME;