CREATE PROCEDURE prc_cust_add(
	IN C_NUM INTEGER,
	IN C_LNAME VARCHAR(20),
	IN C_FNAME VARCHAR(20),
	IN C_BAL DOUBLE
)
INSERT INTO CUST_MYSQL(CUST_NUM,CUST_LNAME,CUST_FNAME,CUST_BALANCE) VALUES(C_NUM,C_LNAME,C_FNAME,C_BAL);
CALL prc_cust_add(2003,'Rauthor','Peter',0.00);
SELECT * FROM CUST_MYSQL;