SELECT DISTINCT A.CUST_CODE, A.CUST_FNAME, A.CUST_LNAME
FROM (SELECT  C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME
  FROM LGCUSTOMER C, LGINVOICE I
  WHERE C.CUST_CODE = I.CUST_CODE AND 
  EMPLOYEE_ID = 83649) A,
  (SELECT  C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME
  FROM LGCUSTOMER C, LGINVOICE I
  WHERE C.CUST_CODE = I.CUST_CODE AND 
  EMPLOYEE_ID = 83677) B
WHERE A.CUST_CODE = B.CUST_CODE
ORDER BY A.CUST_LNAME ASC, A.CUST_FNAME ASC;
