SELECT ASSIGNMENT.EMP_NUM, EMP_LNAME,
ROUND(SUM(ASSIGNMENT.ASSIGN_HOURS),1) AS SumOfASSIGN_HOURS,
SUM(ROUND((ASSIGNMENT.ASSIGN_CHG_HR * ASSIGNMENT.ASSIGN_HOURS),2)) AS SumOfASSIGN_CHARGE
FROM EMPLOYEE, ASSIGNMENT
WHERE EMPLOYEE.EMP_NUM = ASSIGNMENT.EMP_NUM
GROUP BY ASSIGNMENT.EMP_NUM, EMP_LNAME
ORDER BY ASSIGNMENT.EMP_NUM;
