SELECT M.EMP_FNAME AS MGR_FNAME, M.EMP_LNAME AS MGR_LNAME, 
	D.DEPT_NAME, D.DEPT_PHONE, E.EMP_FNAME, E.EMP_LNAME,
	C.CUST_LNAME, I.INV_DATE, I.INV_TOTAL
FROM LGDEPARTMENT AS D, LGEMPLOYEE AS E, LGEMPLOYEE AS M, 
  LGINVOICE AS I, LGCUSTOMER AS C
WHERE D.EMP_NUM = M.EMP_NUM
   AND D.DEPT_NUM = E.DEPT_NUM
   AND E.EMP_NUM = I.EMPLOYEE_ID
   AND I.CUST_CODE = C.CUST_CODE
   AND CUST_LNAME = 'HAGAN'
   AND INV_DATE = "2017-05-18";
