CREATE TABLE INVOICE (
    INV_NUM INT,
    CUST_NUM INT,
    INV_DATE DATE,
    INV_AMOUNT DECIMAL(10,2),
    PRIMARY KEY (INV_NUM),
    CONSTRAINT FK_CUST_NUM FOREIGN KEY (CUST_NUM) REFERENCES CUSTOMER(CUST_NUM)
);
