SELECT DISTINCT A.EMP_NUM, A.EMP_LNAME, A.EMP_EMAIL, 
A.EMP_TITLE, B.DEPT_NAME
FROM LGEMPLOYEE A
INNER JOIN LGDEPARTMENT B ON A.DEPT_NUM = B.DEPT_NUM
WHERE A.EMP_TITLE LIKE '%ASSOCIATE'
ORDER BY B.DEPT_NAME ASC, A.EMP_TITLE ASC, A.EMP_NUM ASC;
