SELECT E.EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL, TOTAL
FROM LGEMPLOYEE E 
INNER JOIN
	(SELECT EMPLOYEE_ID, SUM(LINE_QTY) AS TOTAL
	FROM LGINVOICE I 
	INNER JOIN LGLINE L 
	ON I.INV_NUM = L.INV_NUM
	INNER JOIN LGPRODUCT P 
	ON L.PROD_SKU = P.PROD_SKU
	INNER JOIN LGBRAND B 
	ON B.BRAND_ID = P.BRAND_ID
	WHERE BRAND_NAME = 'BINDER PRIME'
	AND INV_DATE BETWEEN '2017-11-01' AND '2017-12-05'
GROUP BY EMPLOYEE_ID) S1
ON E.EMP_NUM = S1.EMPLOYEE_ID
WHERE TOTAL = (SELECT MAX(TOTAL)
	FROM (SELECT EMPLOYEE_ID, SUM(LINE_QTY) AS TOTAL
	FROM LGINVOICE I 
	INNER JOIN LGLINE L 
	ON I.INV_NUM = L.INV_NUM
	INNER JOIN LGPRODUCT P 
	ON L.PROD_SKU = P.PROD_SKU
	INNER JOIN LGBRAND B 
	ON B.BRAND_ID = P.BRAND_ID
	WHERE BRAND_NAME = 'BINDER PRIME'
	AND INV_DATE BETWEEN '2017-11-01' AND '2017-12-05'
	GROUP BY EMPLOYEE_ID) S2)
  ORDER BY E.EMP_LNAME ASC;
