DELIMITER $$

CREATE PROCEDURE prc_cus_balance_update(INV_NUM INT)
BEGIN
  DECLARE SUBTOTAL DECIMAL(10,2);
	SELECT INV_TOTAL INTO SUBTOTAL 
		FROM INVOICE
		WHERE INV_NUMBER = INV_NUM;
	UPDATE CUSTOMER SET
		CUS_BALANCE = CUS_BALANCE + SUBTOTAL;
END; 

$$
