UPDATE CHARTER
SET CHAR_WAIT_CHG =
(SELECT MOD_CHG_MILE 
	FROM MODEL,AIRCRAFT 
	WHERE MODEL.MOD_CODE = AIRCRAFT.MOD_CODE
	AND AIRCRAFT.AC_NUMBER = CHARTER.AC_NUMBER);
ALTER TABLE MODEL ADD MOD_WAIT_CHG DECIMAL(7, 2);