SELECT A.CUST_CODE, A.CUST_FNAME, A.CUST_LNAME, SUM(B.INV_TOTAL) AS TOTALINVOICES
FROM LGCUSTOMER A
INNER JOIN LGINVOICE B ON (A.CUST_CODE = B.CUST_CODE)
GROUP BY A.CUST_CODE 
HAVING SUM(B.INV_TOTAL) > 1500
ORDER BY TOTALINVOICES DESC;
