CREATE PROCEDURE prc_inv_add(
	I_NUM INTEGER,
	C_NUM INTEGER,
	I_DATE DATE,
	I_AMOUNT DOUBLE
)
INSERT INTO INV_MYSQL(INV_NUM,CUST_NUM,INV_DATE,INV_AMOUNT) VALUES(I_NUM,C_NUM,I_DATE,I_AMOUNT);

CALL prc_inv_add(9006,2000,'2018-04-30',301.72);
SELECT * FROM INV_MYSQL;