SELECT DISTINCT A.CUST_FNAME, A.CUST_LNAME, A.CUST_STREET, 
A.CUST_CITY, A.CUST_STATE, A.CUST_ZIP
FROM LGCUSTOMER A
INNER JOIN LGINVOICE B ON A.CUST_CODE = B.CUST_CODE
INNER JOIN LGLINE C ON B.INV_NUM = C.INV_NUM
INNER JOIN LGPRODUCT D ON C.PROD_SKU = D.PROD_SKU
INNER JOIN LGBRAND E ON D.BRAND_ID = E.BRAND_ID 
WHERE E.BRAND_NAME = 'Foresters Best' AND D.PROD_CATEGORY = 'top coat'
AND B.INV_DATE  BETWEEN '2017-7-15' AND '2017-7-31'
GROUP BY A.CUST_FNAME, A.CUST_LNAME, A.CUST_STREET, A.CUST_CITY, A.CUST_STATE, A.CUST_ZIP
ORDER BY A.CUST_STATE ASC, A.CUST_LNAME ASC, A.CUST_FNAME ASC;