ALTER TABLE CHARTER
ADD CHAR_WAIT_CHG DECIMAL (6, 2),
ADD CHAR_FLT_CHG_HR DECIMAL (6, 2),
ADD CHAR_FLT_CHG DECIMAL (10, 2),
ADD CHAR_TAX_CHG DECIMAL (6, 2),
ADD CHAR_TOT_CHG DECIMAL (10, 2),
ADD CHAR_PYMT DECIMAL (10, 2),
ADD CHAR_BALANCE DECIMAL (10, 2);